package com.aicode.review.service;

import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.body.Parameter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Documentation Generator feature: automatically produces class docs, method
 * docs, a simple API doc listing of public methods, and a README summary,
 * straight from the parsed source (no AI call required, so it always works).
 */
@Slf4j
@Service
public class DocumentationGeneratorService {

    public String generateMarkdownDocs(List<Path> javaFiles, String projectName) {
        StringBuilder sb = new StringBuilder();
        sb.append("# ").append(projectName).append(" - Generated Documentation\n\n");
        sb.append("_Auto-generated by AI Code Review Assistant._\n\n");
        sb.append("## Table of Contents\n");

        List<CompilationUnit> units = javaFiles.stream()
                .filter(p -> p.getFileName().toString().endsWith(".java"))
                .map(this::safeParse)
                .filter(cu -> cu != null)
                .collect(Collectors.toList());

        for (CompilationUnit cu : units) {
            for (ClassOrInterfaceDeclaration c : cu.findAll(ClassOrInterfaceDeclaration.class)) {
                sb.append("- [").append(c.getNameAsString()).append("](#").append(c.getNameAsString().toLowerCase()).append(")\n");
            }
        }
        sb.append("\n---\n\n");

        for (CompilationUnit cu : units) {
            for (ClassOrInterfaceDeclaration c : cu.findAll(ClassOrInterfaceDeclaration.class)) {
                sb.append("## ").append(c.getNameAsString()).append("\n\n");
                sb.append("**Type:** ").append(c.isInterface() ? "Interface" : "Class").append("  \n");
                sb.append("**Modifiers:** ").append(modifiers(c.getModifiers().toString())).append("\n\n");

                c.getComment().ifPresent(comment -> sb.append(clean(comment.getContent())).append("\n\n"));

                List<MethodDeclaration> methods = c.getMethods();
                if (!methods.isEmpty()) {
                    sb.append("### Methods\n\n");
                    for (MethodDeclaration m : methods) {
                        String params = m.getParameters().stream()
                                .map(this::formatParam)
                                .collect(Collectors.joining(", "));
                        sb.append("#### `").append(m.getTypeAsString()).append(" ").append(m.getNameAsString())
                          .append("(").append(params).append(")`\n\n");
                        m.getComment().ifPresent(comment -> sb.append(clean(comment.getContent())).append("\n\n"));
                        if (!m.getParameters().isEmpty()) {
                            sb.append("**Parameters:**\n");
                            for (Parameter p : m.getParameters()) {
                                sb.append("- `").append(p.getNameAsString()).append("`: ").append(p.getTypeAsString()).append("\n");
                            }
                            sb.append("\n");
                        }
                        sb.append("**Returns:** `").append(m.getTypeAsString()).append("`\n\n");
                    }
                }
                sb.append("---\n\n");
            }
        }

        return sb.toString();
    }

    public String generateApiDocSummary(List<Path> javaFiles) {
        StringBuilder sb = new StringBuilder();
        sb.append("# API Documentation Summary\n\n");
        sb.append("Public methods discovered across the uploaded project:\n\n");
        sb.append("| Class | Method | Return Type | Parameters |\n|---|---|---|---|\n");

        for (Path file : javaFiles) {
            if (!file.getFileName().toString().endsWith(".java")) continue;
            CompilationUnit cu = safeParse(file);
            if (cu == null) continue;

            for (ClassOrInterfaceDeclaration c : cu.findAll(ClassOrInterfaceDeclaration.class)) {
                for (MethodDeclaration m : c.getMethods()) {
                    if (!m.isPublic()) continue;
                    String params = m.getParameters().stream().map(this::formatParam).collect(Collectors.joining(", "));
                    sb.append("| ").append(c.getNameAsString()).append(" | ").append(m.getNameAsString())
                      .append(" | ").append(m.getTypeAsString()).append(" | ").append(params).append(" |\n");
                }
            }
        }
        return sb.toString();
    }

    public String generateReadmeSummary(String projectName, int numClasses, int numMethods, int loc, int qualityScore) {
        return "# " + projectName + "\n\n"
                + "Auto-generated summary from AI Code Review Assistant.\n\n"
                + "## Overview\n"
                + "- Classes: " + numClasses + "\n"
                + "- Methods: " + numMethods + "\n"
                + "- Lines of Code: " + loc + "\n"
                + "- Code Quality Score: " + qualityScore + "/100\n\n"
                + "## Getting Started\n"
                + "Add setup and usage instructions here.\n\n"
                + "## License\n"
                + "Add your license here.\n";
    }

    private String formatParam(Parameter p) {
        return p.getTypeAsString() + " " + p.getNameAsString();
    }

    private String modifiers(String raw) {
        return raw.replace("[", "").replace("]", "");
    }

    private String clean(String comment) {
        return comment.replaceAll("(?m)^\\s*\\*\\s?", "").trim();
    }

    private CompilationUnit safeParse(Path file) {
        try {
            return StaticJavaParser.parse(file);
        } catch (Exception e) {
            log.warn("Could not parse {} for documentation: {}", file, e.getMessage());
            return null;
        }
    }
}
